/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kpp_3_4;

import java.awt.FileDialog;
import java.awt.List;
import java.beans.XMLDecoder;
import java.beans.XMLEncoder;
import java.io.BufferedOutputStream;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.nio.charset.Charset;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kpuccmajl
 */
public class MainWindow extends javax.swing.JFrame {

    ArrayList<Athlete> AthletesList;
    ArrayList<Athlete> searchAthletes;

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        this.searchAthletes = new ArrayList();
        this.AthletesList = new ArrayList();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSaveTxt = new javax.swing.JButton();
        btnLoadTxt = new javax.swing.JButton();
        btnSaveXml = new javax.swing.JButton();
        btnLoadXml = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAthletes = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblAgeAveValue = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        editSearch = new javax.swing.JTextField();
        btnFIO = new javax.swing.JButton();
        btnRank = new javax.swing.JButton();
        btnHeft = new javax.swing.JButton();
        btnCountCompetetion = new javax.swing.JButton();
        btnNumberPoint = new javax.swing.JButton();
        btnDate = new javax.swing.JButton();
        btnShowAll = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        newFIO = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        newRank = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        newHeft = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        newCountCompetition = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        newNumberPoint = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        newDay = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        newMonth = new javax.swing.JSpinner();
        newYear = new javax.swing.JSpinner();
        btnAddNew = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Таблица итогов Соревнований");

        btnSaveTxt.setText("Сохранить");
        btnSaveTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveTxtActionPerformed(evt);
            }
        });

        btnLoadTxt.setText("Загрузить");
        btnLoadTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadTxtActionPerformed(evt);
            }
        });

        btnSaveXml.setText("Сохранить");
        btnSaveXml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveXmlActionPerformed(evt);
            }
        });

        btnLoadXml.setText("Загрузить");
        btnLoadXml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadXmlActionPerformed(evt);
            }
        });

        tableAthletes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Authlet", "Rank", "CountCompetition", "Heft", "NumberPoint", "Day", "Month", "Year"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableAthletes);

        btnDelete.setText("Удалить выбранный");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jLabel1.setText("Работа с Xml");

        jLabel2.setText("Работа с Txt");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Среднее геометрическое очков");

        jLabel4.setText("Поиск по");

        btnFIO.setText("ФИО");
        btnFIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFIOActionPerformed(evt);
            }
        });

        btnRank.setText("Разряд");
        btnRank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRankActionPerformed(evt);
            }
        });

        btnHeft.setText("Количество соревнований");
        btnHeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHeftActionPerformed(evt);
            }
        });

        btnCountCompetetion.setText("Вес");
        btnCountCompetetion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCountCompetetionActionPerformed(evt);
            }
        });

        btnNumberPoint.setText("Набрано очков");
        btnNumberPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumberPointActionPerformed(evt);
            }
        });

        btnDate.setText("Дата");

        btnShowAll.setText("Отобразить каталог без поиска");
        btnShowAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowAllActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel5.setText("Добавление");

        jLabel6.setText("ФИО");

        jLabel7.setText("Разряд");

        jLabel8.setText("Количество пройденных соревнований");

        jLabel9.setText("Вес участника");

        jLabel10.setText("Набрано очков");

        jLabel11.setText("ДД");

        newDay.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));

        jLabel12.setText("ГГ");

        jLabel13.setText("ММ");

        newMonth.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));

        newYear.setModel(new javax.swing.SpinnerNumberModel(1900, 1900, 2017, 1));

        btnAddNew.setText("Добавить спротсмена");
        btnAddNew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddNewMouseClicked(evt);
            }
        });
        btnAddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(newFIO, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(newRank, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(newHeft, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addComponent(newCountCompetition, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)
                                    .addComponent(newNumberPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(newDay, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnAddNew)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(newMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(newYear)))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newFIO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newRank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newHeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newCountCompetition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newNumberPoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(newDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(newMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btnAddNew)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnRank)
                                            .addComponent(btnFIO))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnCountCompetetion)
                                            .addComponent(btnHeft))
                                        .addGap(53, 53, 53)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnNumberPoint)
                                            .addComponent(btnDate))
                                        .addGap(35, 35, 35)
                                        .addComponent(btnShowAll, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(editSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblAgeAveValue))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(598, 598, 598)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(115, 115, 115))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnSaveXml)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnLoadXml)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(btnSaveTxt)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnLoadTxt)))
                            .addComponent(jLabel2)))
                    .addComponent(btnDelete))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDate)
                            .addComponent(btnCountCompetetion)
                            .addComponent(btnRank)))
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(editSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addComponent(jLabel3)
                                .addGap(176, 176, 176)
                                .addComponent(lblAgeAveValue))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnFIO)
                                    .addComponent(btnHeft)
                                    .addComponent(btnNumberPoint)
                                    .addComponent(btnShowAll))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addComponent(btnDelete)
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveTxt)
                    .addComponent(btnLoadTxt))
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLoadXml)
                        .addGap(4, 4, 4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSaveXml)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveTxtActionPerformed
        FileDialog fd = new FileDialog(this, "Choose a file", FileDialog.SAVE);
        fd.setVisible(true);
        String filename = fd.getDirectory() + fd.getFile();

        ArrayList<String> lines;
        lines = new ArrayList();

        String tmp;
        for (Athlete a : AthletesList) {
            tmp = a.FIO + '|' + a.Rank + '|'
                    + a.Heft + '|' + a.CountCompetition + '|'
                    + a.NumberPoint + '|' + String.valueOf(a.Day) + '|'
                    + String.valueOf(a.Month) + '|' + String.valueOf(a.Year);

            lines.add(tmp);
        }

        Path file = Paths.get(filename);
        try {
            Files.write(file, lines, Charset.forName("UTF-8"));
        } catch (IOException e) {
        }

    }//GEN-LAST:event_btnSaveTxtActionPerformed

    private void btnShowAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowAllActionPerformed
        ShowAllAthletes();
    }//GEN-LAST:event_btnShowAllActionPerformed

    private void btnAddNewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddNewMouseClicked

    }//GEN-LAST:event_btnAddNewMouseClicked

    private void btnAddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewActionPerformed
        Athlete newAthlete = new Athlete();
        newAthlete.FIO = newFIO.getText();
        newAthlete.Rank = newRank.getText();
        newAthlete.Heft = newHeft.getText();
        newAthlete.CountCompetition = newCountCompetition.getText();
        newAthlete.NumberPoint = newNumberPoint.getText();
        newAthlete.Day = (int) newDay.getValue();
        newAthlete.Month = (int) newMonth.getValue();
        newAthlete.Year = (int) newYear.getValue();

        AthletesList.add(newAthlete);
        ShowAllAthletes();

        newFIO.setText("");
        newRank.setText("");
        newHeft.setText("");
        newCountCompetition.setText("");
        newNumberPoint.setText("");
    }//GEN-LAST:event_btnAddNewActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        DefaultTableModel model = (DefaultTableModel) tableAthletes.getModel() ; ////////////////////////////////////////////////////////////////////////
        AthletesList.remove(tableAthletes.getSelectedRow());
        model.removeRow(tableAthletes.getSelectedRow());

        ShowAllAthletes();
    }//GEN-LAST:event_btnDeleteActionPerformed


    private void btnFIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFIOActionPerformed
        searchAthletes.clear();
        for (Athlete a : AthletesList) {
            if (a.FIO.contains(editSearch.getText())) {
                searchAthletes.add(a);
            }
        }
        //Show search
        DefaultTableModel model = (DefaultTableModel) tableAthletes.getModel();
        model.setRowCount(0);
        searchAthletes.forEach((newAthlete) -> {
            model.addRow(new Object[]{newAthlete.FIO, newAthlete.Rank, newAthlete.Heft, newAthlete.CountCompetition, newAthlete.NumberPoint, newAthlete.Day, newAthlete.Month, newAthlete.Year});
        });
    }//GEN-LAST:event_btnFIOActionPerformed

    private void btnRankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRankActionPerformed
        // TODO add your handling code here:
        searchAthletes.clear();
        for (Athlete a : AthletesList) {
            if (a.Rank.contains(editSearch.getText())) {
                searchAthletes.add(a);
            }
        }
        //Show search
        DefaultTableModel model = (DefaultTableModel) tableAthletes.getModel();
        model.setRowCount(0);
        searchAthletes.forEach((newAthlete) -> {
            model.addRow(new Object[]{newAthlete.FIO, newAthlete.Rank, newAthlete.Heft, newAthlete.CountCompetition, newAthlete.NumberPoint, newAthlete.Day, newAthlete.Month, newAthlete.Year});
        });
    }//GEN-LAST:event_btnRankActionPerformed

    private void btnHeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHeftActionPerformed
        searchAthletes.clear();
        for (Athlete a : AthletesList) {
            if (a.Heft.contains(editSearch.getText())) {
                searchAthletes.add(a);
            }
        }
        //Show search
        DefaultTableModel model = (DefaultTableModel) tableAthletes.getModel();
        model.setRowCount(0);
        searchAthletes.forEach((newAthlete) -> {
            model.addRow(new Object[]{newAthlete.FIO, newAthlete.Rank, newAthlete.Heft, newAthlete.CountCompetition, newAthlete.NumberPoint, newAthlete.Day, newAthlete.Month, newAthlete.Year});
        });
    }//GEN-LAST:event_btnHeftActionPerformed

    private void btnCountCompetetionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCountCompetetionActionPerformed
        searchAthletes.clear();
        for (Athlete a : AthletesList) {
            if (a.CountCompetition.contains(editSearch.getText())) {
                searchAthletes.add(a);
            }
        }
        //Show search
        DefaultTableModel model = (DefaultTableModel) tableAthletes.getModel();
        model.setRowCount(0);
        searchAthletes.forEach((newAthlete) -> {
            model.addRow(new Object[]{newAthlete.FIO, newAthlete.Rank, newAthlete.Heft, newAthlete.CountCompetition, newAthlete.NumberPoint, newAthlete.Day, newAthlete.Month, newAthlete.Year});
        });
    }//GEN-LAST:event_btnCountCompetetionActionPerformed

    private void btnNumberPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumberPointActionPerformed
        searchAthletes.clear();
        for (Athlete a : AthletesList) {
            if (a.NumberPoint.contains(editSearch.getText())) {
                searchAthletes.add(a);
            }
        }
        //Show search
        DefaultTableModel model = (DefaultTableModel) tableAthletes.getModel();
        model.setRowCount(0);
        searchAthletes.forEach((newAthlete) -> {
            model.addRow(new Object[]{newAthlete.FIO, newAthlete.Rank, newAthlete.Heft, newAthlete.CountCompetition, newAthlete.NumberPoint, newAthlete.Day, newAthlete.Month, newAthlete.Year});
        });
    }//GEN-LAST:event_btnNumberPointActionPerformed

    private void btnLoadTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadTxtActionPerformed
        FileDialog fd = new FileDialog(this, "Choose a file", FileDialog.LOAD);
        fd.setVisible(true);
        String filename = fd.getDirectory() + fd.getFile();

        AthletesList.clear();
        Athlete tempAthlete;
        Path file = Paths.get(filename);
        java.util.List<String> lines = null;
        try {
            Charset charset = Charset.forName("UTF-8");
            lines = Files.readAllLines(file, charset);
        } catch (IOException e) {
        }

        String[] tempStrList;
        for (String line : lines) {
            if (line.length() < 5) {
                break;
            }
            tempStrList = line.split("\\|");

            tempAthlete = new Athlete();

            tempAthlete.FIO = tempStrList[0];
            tempAthlete.Rank = tempStrList[1];
            System.out.println(tempAthlete.Rank);
            tempAthlete.Heft = tempStrList[2];
            tempAthlete.CountCompetition = tempStrList[3];
            tempAthlete.NumberPoint = tempStrList[4];
            tempAthlete.Day = Integer.parseInt(tempStrList[5]);
            tempAthlete.Month = Integer.parseInt(tempStrList[6]);
            tempAthlete.Year = Integer.parseInt(tempStrList[7]);

            AthletesList.add(tempAthlete);
        }

        ShowAllAthletes();
    }//GEN-LAST:event_btnLoadTxtActionPerformed

    private void btnLoadXmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadXmlActionPerformed
        FileDialog fd = new FileDialog(this, "Choose a file", FileDialog.LOAD);
        fd.setVisible(true);
        String filename = fd.getDirectory() + fd.getFile();

        AthletesList.clear();

        try {
            FileInputStream inputStream = new FileInputStream(filename);
            XMLDecoder decoder = new XMLDecoder(inputStream);
            AthletesList = (ArrayList<Athlete>) decoder.readObject();
            decoder.close();
        } catch (Exception ex) {
        }

        ShowAllAthletes();
    }//GEN-LAST:event_btnLoadXmlActionPerformed

    private void btnSaveXmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveXmlActionPerformed
        FileDialog fd = new FileDialog(this, "Choose a file", FileDialog.SAVE);
        fd.setVisible(true);
        String filename = fd.getDirectory() + fd.getFile();

        try {
            FileOutputStream outputStream = new FileOutputStream(filename);
            XMLEncoder encoder = new XMLEncoder(outputStream);
            encoder.writeObject(AthletesList);
            encoder.close();
            Thread.sleep(10000);
        } catch (Exception ex) {
        }

    }//GEN-LAST:event_btnSaveXmlActionPerformed

    public void ShowAllAthletes() {
        DefaultTableModel model = (DefaultTableModel) tableAthletes.getModel();
        model.setRowCount(0);
        AthletesList.forEach((newAthlete) -> {
            model.addRow(new Object[]{newAthlete.FIO, newAthlete.Rank, newAthlete.Heft, newAthlete.CountCompetition, newAthlete.NumberPoint, newAthlete.Day, newAthlete.Month, newAthlete.Year});
        });

        Runnable task = () -> {
            double Count = Double.valueOf(AthletesList.size());
            
            double gem = 1;
            for (Athlete a : AthletesList) {
                gem *= Double.valueOf(a.NumberPoint);   
            }
            if (Count != 0) {
                lblAgeAveValue.setText(String.valueOf(Math.pow(gem,1/Count)));
                System.out.println(gem);
            } else {
                lblAgeAveValue.setText(String.valueOf(0));
            }
        };

        Thread thread = new Thread(task);
        thread.start();

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainWindow().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNew;
    private javax.swing.JButton btnCountCompetetion;
    private javax.swing.JButton btnDate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFIO;
    private javax.swing.JButton btnHeft;
    private javax.swing.JButton btnLoadTxt;
    private javax.swing.JButton btnLoadXml;
    private javax.swing.JButton btnNumberPoint;
    private javax.swing.JButton btnRank;
    private javax.swing.JButton btnSaveTxt;
    private javax.swing.JButton btnSaveXml;
    private javax.swing.JButton btnShowAll;
    private javax.swing.JTextField editSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAgeAveValue;
    private javax.swing.JTextField newCountCompetition;
    private javax.swing.JSpinner newDay;
    private javax.swing.JTextField newFIO;
    private javax.swing.JTextField newHeft;
    private javax.swing.JSpinner newMonth;
    private javax.swing.JTextField newNumberPoint;
    private javax.swing.JTextField newRank;
    private javax.swing.JSpinner newYear;
    private javax.swing.JTable tableAthletes;
    // End of variables declaration//GEN-END:variables
}
